networks:
  my-network:  
services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'

  mongodb:
      container_name: mongodb
      image: mongo:8.0-rc
      restart: always
      environment: 
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: secret
      ports:
        - '27017:27017'
      networks:
        - my-network
      volumes:
        - ./data:/data/db 

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
    - '6379:6379'
    networks:
      - redis-network

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - express-network
    depends_on:
      - mongodb